version: '3'

services:
  db:
    restart: always

  api:
    command: sh -c "npm run build && npm run start"
    expose:
      - 4000
    restart: always
    volumes:
      - public:/app/public
    environment:
      - NODE_ENV=production

  web-client:
    command: sh -c "npm run build"
    volumes:
      - web-client-build:/app/build
    environment:
      - NODE_ENV=production
      - REACT_APP_API_BASE_URL=/api

  nginx:
    image: nginx:1.19.10
    restart: always
    ports:
      - ${GATEWAY_PORT}:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - web-client-build:/web-client-build
      - public:/public

volumes:
  web-client-build:
  public:
